config/routes.rb
Rails.application.routes.draw do
  root 'playlists#index'
  devise_for :users
  resources :playlists do
    resources :songs
  end

  match 'search', to: 'playlists#search', via: :get

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :playlist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  require 'soundcloud'

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.save
    redirect_to playlists_path
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
  end

  def search
    client = Soundcloud.new(client_id: '8e9e076931762d84d99f341ccb71fe3f')
    @tracks = client.get('/tracks', q: params[:q])
    @playlist = Playlist.find(params[:playlist_id])
    respond_to do |format|
      format.js
    end
  end


  private

  def playlist_params
    params.require(:playlist).permit(:name, :description)
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  require 'soundcloud'

  def create
    @playlist = Playlist.find(params[:playlist_id])
    @song = @playlist.songs.new(title: params[:title], permalink_url: params[:permalink_url],
      soundcloud_id: params[:soundcloud_id], stream_url: params[:stream_url])
    if @song.save
      redirect_to playlist_path(@playlist)
    end
  end


end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundCloud</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag '//connect.soundcloud.com/sdk.js' %>
</head>
<body>



  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
  <div class='row header'>
    <h1><a href="/">SC JUKEBOX</a></h1>
   <nav class="top-bar">
    <ul class="title-area">
      <li class="name">

      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Create Playlist', new_playlist_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
    <hr>
  </nav>
  </div>

  <%= yield %>

  <%= javascript_include_tag 'application' %>


  <%= yield :extra_footer %>
</body>
</html>

app/views/playlists/index.html.erb
<div class='row'>
<h3>Top Playlists:</h3>
<% @playlists.each do |playlist| %>
<h4><%= link_to playlist.name , playlist_path(playlist) %></h4>
<% end %>
</div>

app/views/playlists/new.html.erb
<div class="row">
<h1> Create Playlist </h1>

<%= form_for [ @playlist ] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <%= f.submit class: "button" %>
  <% end %>
</div>

app/views/playlists/search.js.erb
$('#results').empty();
<% @tracks.each do |track| %>
 $('#results').append('<li><%=  link_to track.title, playlist_songs_path(@playlist, soundcloud_id: track.id, title: track.title, permalink_url: track.permalink_url, stream_url: track.stream_url ), method: 'post' %></li>');
<% end %>

app/views/playlists/show.html.erb
<br>
<div class="row">
  <div class="small-6 columns">

    <div class="row master-control">
      <div class="small-6 columns">
        <a href="#" onClick="playFirst()"><i class="fa fa-play"></i></a>
        <a href="#" onClick="stopAll()"><i class="fa fa-stop"></i></a>
        <a href="#" onClick="prevTrack()"><i class="fa fa-backward"></i></a>
        <a href="#" onClick="nextTrack()"><i class="fa fa-forward"></i></a>

      </div>
      <div class="small-6 columns">
    <div id="slider">
    </div>
    </div>
  </div>
    <div id="playlist">

      <% @playlist.songs.each do |song| %>
      <div class="song not-playing"><i class="fa fa-play-circle-o"></i>
        <%= link_to song.title , '#', onclick: "playTrack(this.id)", id: song.soundcloud_id, class: 'playlink' %>
      </div>
      <% end %>
    </div>

  </div>

  <div class="small-6 columns">
    <h2><%= @playlist.name %></h2>
    <h3><%= @playlist.description %></h3>
    <hr>
    <p>Search</p>

    <%= form_tag('/search', remote: true , method: "get") do %>
    <%= label_tag(:q, "") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search", class: "button")  %>
    <%= hidden_field_tag :playlist_id, params[:id]%>
    <% end %>

    <ul id="results">

    </ul>
  </div>

</div>